---
# tasks file for gunicorn
- name: Copy gunicorn code
  copy:
    src: ./config/gunicorn.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"
  tags: gunicorn-systemd-file

- name: systemd daemon-reload
  command: systemctl daemon-reload
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: systemd-daemon-reload