- name: Deploy a Database
  hosts: db_servers
  become: yes
  roles:
    - python
    - mysql_db

- name: Deploy a web application
  hosts: web_servers
  become: yes
  roles:
    - pyenv
    - python
    - nginxinc.nginx
    - nginx_config
    - gunicorn
    - flask_web