---
# tasks file for flask_web
- name: Install python flask dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - flask
    - flask-mysql
    - PyMySql
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask

- git:
    repo: 'https://github.com/manab1200/ansible-web-application.git'
    dest: /opt/ansible-web-application/
    clone: yes
  tags: git-clone

#- name: Copy web-server code
#  copy:
#    src: ./app.py
#    dest: /opt/ansible-web-application/app.py
#    mode: 0755
#  ignore_errors: "{{ ansible_check_mode }}"
#  tags: flask-copy-code
#
#- name: Copy gunicorn conf
#  copy:
#    src: ./gunicorn.py
#    dest: /opt/ansible-web-application/gunicorn.py
#    mode: 0755
#  ignore_errors: "{{ ansible_check_mode }}"
#  tags: gunicorn-conf


- name: Copy nginx config
  copy:
    src: ./flask.conf
    dest: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"
  tags: nginx-config

- name: Copy web-server code
  copy:
    src: ./gunicorn.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"
  tags: gunicorn-systemd-file

- name: Copy web-server code
  copy:
    src: ./flask_app.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask-copy-systemd-file

- name: systemd daemon-reload
  command: systemctl daemon-reload
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: systemd-daemon-reload

- name: Start web-application
  service:
    name: flask_app
    state: started
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask-start
