---
# tasks file for flask_web
- name: Install python flask dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - flask
    - flask-mysql
    - PyMySql
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask

- git:
    repo: 'https://github.com/manab1200/ansible-web-application.git'
    dest: /opt/ansible-web-application/
    clone: yes
  tags: git-clone

- name: Copy web-server code
  copy:
    src: ./app.py
    dest: /opt/app.py
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask-copy-code

- name: Copy web-server code
  copy:
    src: ./flask_app.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask-copy-systemd-file

- name: systemd daemon-reload
  command: systemctl daemon-reload
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: systemd-daemon-reload
  

- name: Start web-application
  service:
    name: flask_app
    state: started
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask-start

#- name: Start web-application
  #shell: python /opt/app.py &
  #ignore_errors: "{{ ansible_check_mode }}"
  #tags: flask-run
