---
# tasks file for flask_web
- name: Install python flask dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - flask
    - flask-mysql
    - PyMySql
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask

- git:
    repo: "https://github.com/manab1200/ansible-web-application"
    dest: /opt/ansible-web-application/
    accept_hostkey: yes
    clone: yes
    #remote: upstream
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: git-clone

- name: Copy web-server code
  copy:
    src: ./config/flask_app.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0755
  ignore_errors: "{{ ansible_check_mode }}"
  tags: flask-copy-systemd-file

- name: systemd daemon-reload
  command: systemctl daemon-reload
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: systemd-daemon-reload
