---
# tasks file for pyenv
- git:
    repo: "git://github.com/pyenv/pyenv.git"
    dest: /root/.pyenv
    accept_hostkey: yes
    clone: yes
    remote: upstream
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: git-clone-pyenv

- blockinfile:
    dest: /root/.bash_profile
    content: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  become: yes
  notify: source bash_profile
  tags: block-in-file

- shell: bash -lc "pyenv versions | grep {{ python_version }}"
  register: pyenv_version
  ignore_errors: yes
  changed_when: False
  tags: pyenv-versions

- shell: bash -lc "pyenv install {{ python_version }}"
  when: pyenv_version|failed

- shell: bash -lc "pyenv local {{ python_version }}"
  args:
    chdir: /opt/ansible-web-application
  when: pyenv_version|failed

- set_fact: ansible_python_interpreter=/root/.pyenv/shims/python

#- pip: name={{ item.name }}
#  with_items:
#  - pip_pkg
#  ignore_errors: yes